services:
  - type: web
    name: quizwin-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
